# Generated by Django 5.2.1 on 2025-05-21 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catimage',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_cats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catimage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_cats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catimage',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
